/* The following code was generated by JFlex 1.4.1 on 23/06/2022 18:30 */

/*
 * Generated on 6/23/22, 5:53 PM
 */
package br.com.davidbuzatto.auroralogo.gui.sh;

import java.io.*;
import javax.swing.text.Segment;

import org.fife.ui.rsyntaxtextarea.*;


/**
 * 
 */

public class AuroraLogoSyntaxHighlighter extends AbstractJFlexCTokenMaker {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int EOL_COMMENT = 2;
  public static final int YYINITIAL = 0;
  public static final int MLC = 1;

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\21\1\10\1\0\1\21\1\17\22\0\1\47\1\67\1\15"+
    "\1\20\1\1\1\32\1\31\1\7\2\30\1\23\1\32\1\27\1\65"+
    "\1\26\1\22\1\4\3\16\4\6\2\3\1\43\1\27\1\64\1\63"+
    "\1\70\1\27\1\20\4\5\1\5\1\5\7\1\1\73\1\72\5\1"+
    "\1\1\5\1\1\30\1\11\1\30\1\17\1\2\1\0\1\50\1\14"+
    "\1\55\1\52\1\42\1\37\1\57\1\33\1\40\1\62\1\1\1\41"+
    "\1\53\1\13\1\56\1\35\1\54\1\51\1\36\1\34\1\12\1\45"+
    "\1\44\1\24\1\1\1\61\1\25\1\71\1\25\1\27\104\0\1\74"+
    "\35\0\1\46\1\0\1\60\5\0\1\66\uff16\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\2\1\2\2\1\3\1\4\2\1\1\5\1\6"+
    "\2\7\1\10\15\1\2\7\3\1\1\11\1\12\5\11"+
    "\1\13\3\11\1\0\2\14\1\3\1\15\1\0\1\3"+
    "\1\0\1\1\2\5\1\16\1\17\1\20\2\1\1\21"+
    "\6\1\1\0\14\1\2\0\1\22\11\0\1\23\1\3"+
    "\1\24\2\3\1\15\1\3\1\0\1\1\1\5\1\25"+
    "\1\5\5\1\1\21\7\1\1\0\15\1\14\0\1\3"+
    "\1\0\1\1\1\5\2\1\1\0\2\1\1\0\6\1"+
    "\1\0\3\1\1\26\4\1\6\0\1\27\2\0\1\30"+
    "\1\0\1\3\1\0\1\5\1\1\1\21\2\1\1\21"+
    "\4\1\1\0\4\1\10\0\1\3\1\5\1\1\1\0"+
    "\3\1\1\0\2\1\5\0\1\1\1\21\2\1\5\0"+
    "\1\1\2\0\1\1\5\0\1\21\60\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[287];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\75\0\172\0\267\0\364\0\u0131\0\u016e\0\u01ab"+
    "\0\267\0\u01e8\0\u0225\0\u0262\0\u029f\0\u02dc\0\267\0\267"+
    "\0\u0319\0\u0356\0\u0393\0\u03d0\0\u040d\0\u044a\0\u0487\0\u04c4"+
    "\0\u0501\0\u053e\0\u057b\0\u05b8\0\u05f5\0\u0632\0\u066f\0\u06ac"+
    "\0\u06e9\0\u0726\0\u0763\0\267\0\u07a0\0\u07dd\0\u081a\0\u0857"+
    "\0\u0894\0\267\0\u08d1\0\u090e\0\u094b\0\u0988\0\u09c5\0\u0a02"+
    "\0\u0a3f\0\267\0\u0a7c\0\u0ab9\0\u0af6\0\u0b33\0\u0b70\0\u0bad"+
    "\0\267\0\267\0\267\0\u0bea\0\u0c27\0\u0c64\0\u0ca1\0\u0cde"+
    "\0\u0d1b\0\u0d58\0\u0d95\0\u0dd2\0\u0e0f\0\u0e4c\0\u0e89\0\u0ec6"+
    "\0\u0f03\0\u0f40\0\u0f7d\0\u0fba\0\u0ff7\0\u1034\0\u1071\0\u10ae"+
    "\0\u10eb\0\u1128\0\u1165\0\267\0\u11a2\0\u11df\0\u121c\0\u1259"+
    "\0\u1296\0\u12d3\0\u1310\0\u134d\0\u138a\0\u0a02\0\u13c7\0\267"+
    "\0\u1404\0\u1441\0\u0a7c\0\u147e\0\u14bb\0\u14f8\0\u1535\0\267"+
    "\0\u1572\0\u15af\0\u15ec\0\u1629\0\u1666\0\u16a3\0\364\0\u16e0"+
    "\0\u171d\0\u175a\0\u1797\0\u17d4\0\u1811\0\u184e\0\u188b\0\u18c8"+
    "\0\u1905\0\u1942\0\u197f\0\u19bc\0\u19f9\0\u1a36\0\u1a73\0\u1ab0"+
    "\0\u1aed\0\u1b2a\0\u1b67\0\u1ba4\0\u1be1\0\u1c1e\0\u1c5b\0\u1c98"+
    "\0\u1cd5\0\u1d12\0\u1d4f\0\u1d8c\0\u1dc9\0\u1e06\0\u1e43\0\u1e80"+
    "\0\u1ebd\0\u1efa\0\u1f37\0\u1f74\0\u1fb1\0\u1fee\0\u202b\0\u2068"+
    "\0\u20a5\0\u20e2\0\u211f\0\u215c\0\u2199\0\u21d6\0\u2213\0\u2250"+
    "\0\u228d\0\u22ca\0\u2307\0\u2344\0\364\0\u2381\0\u23be\0\u23fb"+
    "\0\u2438\0\u2475\0\u24b2\0\u24ef\0\u252c\0\u2569\0\u25a6\0\u25e3"+
    "\0\u2620\0\u265d\0\u269a\0\u26d7\0\u2714\0\u06ac\0\u2751\0\u278e"+
    "\0\u27cb\0\u2808\0\u2845\0\267\0\u2882\0\u28bf\0\u28fc\0\u2939"+
    "\0\u2976\0\u29b3\0\u29f0\0\u2a2d\0\u2a6a\0\u2aa7\0\u2ae4\0\u2b21"+
    "\0\u2b5e\0\u25e3\0\u2b9b\0\u269a\0\u2bd8\0\u2c15\0\u2c52\0\u2c8f"+
    "\0\u2ccc\0\u2d09\0\u2d46\0\u2d83\0\u2dc0\0\u2dfd\0\u2e3a\0\u2e77"+
    "\0\u2eb4\0\u2ef1\0\u2f2e\0\u2f6b\0\u2fa8\0\u2fe5\0\u3022\0\u305f"+
    "\0\u309c\0\u30d9\0\u3116\0\u3153\0\u3190\0\u31cd\0\u320a\0\u3247"+
    "\0\u3284\0\u32c1\0\u32fe\0\u333b\0\u3378\0\u33b5\0\u33f2\0\u342f"+
    "\0\u346c\0\u34a9\0\u34e6\0\u3523\0\u3560\0\u359d\0\u35da\0\u3617"+
    "\0\u3654\0\u3691\0\u36ce\0\u370b\0\u3748\0\u3785\0\u37c2\0\u37ff"+
    "\0\u383c\0\u3879\0\u38b6\0\u38f3\0\u3930\0\u396d\0\u39aa\0\u39e7"+
    "\0\u3a24\0\u3a61\0\u3a9e\0\u3adb\0\u3b18\0\u3b55\0\u3b92\0\u3bcf"+
    "\0\u3c0c\0\u3c49\0\u3c86\0\u3cc3\0\u3d00\0\u3d3d\0\u3d7a\0\u3db7"+
    "\0\u3df4\0\u3e31\0\u3e6e\0\u3eab\0\u3ee8\0\u3f25\0\u3f62";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[287];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\2\5\1\6\1\7\1\5\1\6\1\10\1\11"+
    "\1\4\1\5\1\12\1\13\1\14\1\6\2\4\1\15"+
    "\1\16\1\17\1\5\1\20\2\4\1\20\1\21\1\17"+
    "\1\5\1\22\1\23\1\24\2\5\1\25\1\26\1\4"+
    "\1\5\1\27\1\4\1\15\1\30\1\31\1\32\1\33"+
    "\1\5\1\34\1\5\1\35\1\4\2\5\1\36\1\37"+
    "\1\17\1\40\2\36\1\41\1\5\1\42\1\4\10\43"+
    "\1\44\12\43\1\45\7\43\1\46\3\43\1\47\4\43"+
    "\1\50\30\43\10\51\1\52\22\51\1\53\3\51\1\54"+
    "\4\51\1\55\30\51\76\0\6\5\2\0\1\56\3\5"+
    "\1\0\1\5\5\0\1\5\6\0\10\5\1\0\2\5"+
    "\2\0\10\5\1\0\2\5\7\0\2\5\1\0\3\57"+
    "\2\6\1\57\1\6\2\0\4\57\1\0\1\6\1\0"+
    "\1\57\3\0\1\57\6\0\10\57\1\0\3\57\1\0"+
    "\13\57\3\0\1\57\3\0\6\57\2\6\1\57\1\6"+
    "\2\0\4\57\1\0\1\6\1\0\1\57\3\0\1\60"+
    "\6\0\10\57\1\0\3\57\1\0\13\57\3\0\1\57"+
    "\3\0\3\57\7\61\1\62\1\63\1\64\63\61\1\0"+
    "\6\5\2\0\1\56\3\5\1\0\1\5\5\0\1\5"+
    "\6\0\10\5\1\0\2\5\2\0\10\5\1\65\2\5"+
    "\7\0\2\5\2\0\6\5\2\0\1\56\3\5\1\0"+
    "\1\5\5\0\1\5\6\0\10\5\1\0\2\5\2\0"+
    "\1\5\1\66\6\5\1\0\2\5\7\0\2\5\1\0"+
    "\10\14\1\67\1\70\3\14\1\71\57\14\21\0\1\15"+
    "\25\0\1\15\47\0\1\72\1\73\102\0\1\17\44\0"+
    "\6\5\2\0\1\56\3\5\1\0\1\5\5\0\1\5"+
    "\6\0\10\5\1\0\2\5\2\0\1\5\1\74\6\5"+
    "\1\0\2\5\7\0\2\5\2\0\6\5\2\0\1\56"+
    "\3\5\1\0\1\5\5\0\1\5\6\0\10\5\1\0"+
    "\2\5\2\0\1\5\1\75\6\5\1\0\2\5\7\0"+
    "\2\5\2\0\6\5\2\0\1\56\3\5\1\0\1\5"+
    "\5\0\1\5\6\0\7\5\1\76\1\0\2\5\2\0"+
    "\10\5\1\0\2\5\7\0\2\5\2\0\6\5\2\0"+
    "\1\56\3\5\1\0\1\5\5\0\1\5\6\0\5\5"+
    "\1\77\1\5\1\100\1\0\2\5\2\0\1\101\7\5"+
    "\1\0\2\5\7\0\2\5\2\0\6\5\2\0\1\56"+
    "\1\5\1\102\1\5\1\0\1\5\5\0\1\5\6\0"+
    "\3\5\1\103\4\5\1\0\2\5\2\0\10\5\1\0"+
    "\2\5\7\0\2\5\2\0\6\5\2\0\1\56\3\5"+
    "\1\0\1\5\5\0\1\5\6\0\7\5\1\104\1\0"+
    "\2\5\1\105\1\0\10\5\1\0\2\5\7\0\2\5"+
    "\2\0\6\5\2\0\1\56\2\5\1\106\1\0\1\5"+
    "\5\0\1\5\6\0\10\5\1\0\2\5\2\0\3\5"+
    "\1\107\4\5\1\0\1\110\1\5\7\0\2\5\2\0"+
    "\6\5\2\0\1\56\3\5\1\0\1\5\5\0\1\5"+
    "\6\0\7\5\1\111\1\0\2\5\2\0\1\112\5\5"+
    "\1\113\1\5\1\0\2\5\7\0\2\5\2\0\6\5"+
    "\2\0\1\56\3\5\1\0\1\5\5\0\1\5\6\0"+
    "\5\5\1\114\1\5\1\115\1\0\2\5\2\0\10\5"+
    "\1\0\2\5\7\0\2\5\2\0\6\5\2\0\1\56"+
    "\3\5\1\0\1\5\5\0\1\5\6\0\10\5\1\0"+
    "\2\5\2\0\1\116\7\5\1\0\2\5\7\0\2\5"+
    "\2\0\6\5\2\0\1\56\3\5\1\0\1\5\5\0"+
    "\1\5\6\0\5\5\1\117\1\120\1\5\1\0\2\5"+
    "\2\0\10\5\1\0\2\5\7\0\2\5\2\0\6\5"+
    "\2\0\1\56\3\5\1\0\1\5\5\0\1\5\6\0"+
    "\5\5\1\121\2\5\1\0\2\5\2\0\10\5\1\0"+
    "\2\5\7\0\2\5\64\0\1\17\74\0\1\17\1\0"+
    "\1\17\56\0\1\122\116\0\1\17\4\0\6\5\2\0"+
    "\1\56\3\5\1\0\1\5\5\0\1\5\6\0\10\5"+
    "\1\0\2\5\2\0\10\5\1\0\2\5\7\0\2\5"+
    "\1\123\10\43\1\0\12\43\1\0\7\43\1\0\3\43"+
    "\1\0\4\43\1\0\30\43\22\0\1\124\106\0\1\125"+
    "\74\0\1\126\3\0\1\127\100\0\1\130\30\0\10\51"+
    "\1\0\22\51\1\0\3\51\1\0\4\51\1\0\30\51"+
    "\34\0\1\131\74\0\1\132\3\0\1\133\100\0\1\134"+
    "\42\0\1\135\62\0\7\57\2\0\4\57\1\0\1\57"+
    "\1\0\1\57\3\0\1\57\6\0\10\57\1\0\3\57"+
    "\1\0\13\57\3\0\1\57\3\0\6\57\4\136\2\0"+
    "\3\57\1\136\1\0\1\136\1\0\1\57\3\0\1\57"+
    "\6\0\4\57\1\136\2\57\1\136\1\0\3\57\1\0"+
    "\1\136\1\57\1\136\2\57\1\136\5\57\3\0\1\57"+
    "\3\0\3\57\7\137\1\140\1\0\64\137\7\0\1\140"+
    "\65\0\4\137\1\141\1\137\1\142\1\143\1\0\1\61"+
    "\1\144\3\61\1\141\15\137\1\61\2\137\1\61\11\137"+
    "\1\61\23\137\56\0\1\145\17\0\6\5\2\0\1\56"+
    "\3\5\1\0\1\5\5\0\1\5\6\0\10\5\1\0"+
    "\2\5\2\0\1\146\7\5\1\0\2\5\7\0\2\5"+
    "\1\0\11\67\1\147\3\67\1\150\63\67\1\14\1\67"+
    "\2\14\1\0\1\14\1\151\4\14\15\67\1\14\2\67"+
    "\1\14\11\67\1\14\23\67\1\0\6\5\2\0\1\56"+
    "\3\5\1\0\1\5\5\0\1\5\6\0\10\5\1\0"+
    "\2\5\2\0\6\5\1\152\1\5\1\0\2\5\7\0"+
    "\2\5\2\0\6\5\2\0\1\56\3\5\1\0\1\5"+
    "\5\0\1\5\6\0\7\5\1\153\1\0\2\5\2\0"+
    "\10\5\1\0\2\5\7\0\2\5\2\0\6\5\2\0"+
    "\1\56\1\5\1\154\1\5\1\0\1\5\5\0\1\5"+
    "\6\0\10\5\1\0\2\5\2\0\10\5\1\0\2\5"+
    "\7\0\2\5\2\0\6\5\2\0\1\56\3\5\1\0"+
    "\1\5\5\0\1\5\6\0\10\5\1\0\2\5\2\0"+
    "\3\5\1\155\4\5\1\0\2\5\7\0\2\5\2\0"+
    "\6\5\2\0\1\56\3\5\1\0\1\5\5\0\1\5"+
    "\6\0\10\5\1\0\1\5\1\156\2\0\1\5\1\157"+
    "\6\5\1\0\2\5\7\0\2\5\2\0\6\5\2\0"+
    "\1\56\3\5\1\0\1\5\5\0\1\5\6\0\10\5"+
    "\1\0\2\5\2\0\1\5\1\160\6\5\1\0\2\5"+
    "\7\0\2\5\2\0\6\5\2\0\1\56\3\5\1\0"+
    "\1\5\5\0\1\5\6\0\1\5\1\161\6\5\1\0"+
    "\2\5\2\0\4\5\1\162\2\5\1\163\1\0\2\5"+
    "\7\0\2\5\2\0\6\5\2\0\1\56\3\5\1\0"+
    "\1\5\5\0\1\5\6\0\10\5\1\0\2\5\2\0"+
    "\5\5\1\164\2\5\1\0\2\5\7\0\2\5\2\0"+
    "\6\5\2\0\1\56\3\5\1\0\1\5\5\0\1\5"+
    "\6\0\10\5\1\0\2\5\2\0\1\5\1\165\6\5"+
    "\1\0\1\166\1\5\7\0\2\5\50\0\1\167\26\0"+
    "\6\5\2\0\1\56\3\5\1\0\1\5\5\0\1\5"+
    "\6\0\10\5\1\0\2\5\2\0\1\170\7\5\1\0"+
    "\2\5\7\0\2\5\2\0\6\5\2\0\1\56\3\5"+
    "\1\0\1\5\5\0\1\5\6\0\10\5\1\0\2\5"+
    "\2\0\1\171\7\5\1\0\2\5\7\0\2\5\2\0"+
    "\6\5\2\0\1\56\1\172\2\5\1\0\1\5\5\0"+
    "\1\5\6\0\10\5\1\0\2\5\2\0\10\5\1\0"+
    "\2\5\7\0\2\5\2\0\6\5\2\0\1\56\3\5"+
    "\1\0\1\5\5\0\1\5\6\0\2\5\1\173\5\5"+
    "\1\0\2\5\2\0\10\5\1\0\2\5\7\0\2\5"+
    "\2\0\6\5\2\0\1\56\3\5\1\0\1\5\5\0"+
    "\1\5\6\0\5\5\1\174\2\5\1\0\2\5\2\0"+
    "\10\5\1\0\2\5\7\0\2\5\2\0\6\5\2\0"+
    "\1\56\3\5\1\0\1\5\5\0\1\5\6\0\3\5"+
    "\1\175\4\5\1\0\2\5\2\0\10\5\1\0\2\5"+
    "\7\0\2\5\2\0\6\5\2\0\1\56\3\5\1\0"+
    "\1\5\5\0\1\5\6\0\10\5\1\0\1\5\1\176"+
    "\2\0\10\5\1\0\2\5\7\0\2\5\2\0\6\5"+
    "\2\0\1\56\3\5\1\0\1\5\5\0\1\5\6\0"+
    "\3\5\1\177\4\5\1\0\2\5\2\0\10\5\1\0"+
    "\2\5\7\0\2\5\2\0\6\5\2\0\1\56\3\5"+
    "\1\0\1\5\5\0\1\5\6\0\10\5\1\0\2\5"+
    "\2\0\7\5\1\200\1\0\2\5\7\0\2\5\2\0"+
    "\6\5\2\0\1\56\1\5\1\201\1\5\1\0\1\5"+
    "\5\0\1\5\6\0\10\5\1\0\2\5\2\0\1\202"+
    "\7\5\1\0\2\5\7\0\2\5\2\0\6\5\2\0"+
    "\1\56\3\5\1\0\1\5\5\0\1\5\6\0\10\5"+
    "\1\0\2\5\2\0\1\203\7\5\1\0\2\5\7\0"+
    "\2\5\2\0\6\5\2\0\1\56\3\5\1\0\1\5"+
    "\5\0\1\5\6\0\10\5\1\0\2\5\2\0\1\5"+
    "\1\204\6\5\1\0\2\5\7\0\2\5\41\0\1\205"+
    "\11\0\1\206\1\207\113\0\1\17\36\0\1\210\75\0"+
    "\1\211\100\0\1\212\77\0\1\213\64\0\1\214\75\0"+
    "\1\215\100\0\1\216\77\0\1\217\33\0\4\220\5\0"+
    "\1\220\1\0\1\220\20\0\1\220\2\0\1\220\5\0"+
    "\1\220\1\0\1\220\2\0\1\220\17\0\7\137\1\62"+
    "\1\0\70\137\1\142\1\137\1\142\1\140\1\0\5\137"+
    "\1\142\62\137\1\61\1\137\1\61\1\140\1\0\5\137"+
    "\1\61\61\137\4\221\1\62\1\0\3\137\1\221\1\137"+
    "\1\221\20\137\1\221\2\137\1\221\5\137\1\221\1\137"+
    "\1\221\2\137\1\221\17\137\47\0\1\222\26\0\6\5"+
    "\2\0\1\56\1\5\1\223\1\5\1\0\1\5\5\0"+
    "\1\5\6\0\10\5\1\0\2\5\2\0\10\5\1\0"+
    "\2\5\7\0\2\5\1\0\10\67\1\0\67\67\4\224"+
    "\2\67\1\147\2\67\1\224\1\150\1\224\20\67\1\224"+
    "\2\67\1\224\5\67\1\224\1\67\1\224\2\67\1\224"+
    "\17\67\1\0\6\5\2\0\1\56\3\5\1\0\1\5"+
    "\5\0\1\5\6\0\10\5\1\0\2\5\2\0\5\5"+
    "\1\225\2\5\1\0\2\5\7\0\2\5\2\0\6\5"+
    "\2\0\1\56\3\5\1\0\1\5\5\0\1\5\6\0"+
    "\1\5\1\226\6\5\1\0\2\5\2\0\10\5\1\0"+
    "\2\5\7\0\2\5\2\0\6\5\2\0\1\56\3\5"+
    "\1\0\1\5\5\0\1\5\6\0\10\5\1\0\2\5"+
    "\2\0\10\5\1\227\2\5\7\0\2\5\2\0\6\5"+
    "\2\0\1\56\3\5\1\0\1\5\5\0\1\5\6\0"+
    "\2\5\1\204\5\5\1\0\2\5\2\0\10\5\1\0"+
    "\2\5\7\0\2\5\2\0\6\5\2\0\1\56\3\5"+
    "\1\0\1\5\5\0\1\5\6\0\10\5\1\0\2\5"+
    "\2\0\1\230\7\5\1\0\2\5\7\0\2\5\2\0"+
    "\6\5\2\0\1\56\3\5\1\0\1\5\5\0\1\5"+
    "\6\0\10\5\1\0\2\5\2\0\1\231\7\5\1\0"+
    "\2\5\7\0\2\5\2\0\6\5\2\0\1\56\3\5"+
    "\1\0\1\5\5\0\1\5\6\0\10\5\1\0\2\5"+
    "\2\0\10\5\1\232\2\5\7\0\2\5\2\0\6\5"+
    "\2\0\1\56\1\233\2\5\1\0\1\5\5\0\1\5"+
    "\6\0\10\5\1\0\2\5\2\0\10\5\1\0\2\5"+
    "\7\0\2\5\2\0\6\5\2\0\1\56\3\5\1\0"+
    "\1\5\5\0\1\5\6\0\10\5\1\0\2\5\2\0"+
    "\1\5\1\234\6\5\1\0\2\5\7\0\2\5\2\0"+
    "\6\5\2\0\1\56\1\203\2\5\1\0\1\5\5\0"+
    "\1\5\6\0\10\5\1\0\2\5\2\0\1\5\1\235"+
    "\6\5\1\0\2\5\7\0\2\5\2\0\6\5\2\0"+
    "\1\56\3\5\1\0\1\5\5\0\1\5\6\0\10\5"+
    "\1\0\2\5\2\0\2\5\1\236\1\237\4\5\1\0"+
    "\2\5\7\0\2\5\2\0\6\5\2\0\1\56\3\5"+
    "\1\0\1\5\5\0\1\5\6\0\7\5\1\240\1\0"+
    "\2\5\2\0\10\5\1\0\2\5\7\0\2\5\36\0"+
    "\1\241\40\0\6\5\2\0\1\56\3\5\1\0\1\5"+
    "\5\0\1\5\6\0\5\5\1\242\2\5\1\0\2\5"+
    "\2\0\10\5\1\0\2\5\7\0\2\5\2\0\6\5"+
    "\2\0\1\56\3\5\1\0\1\5\5\0\1\5\6\0"+
    "\10\5\1\0\2\5\2\0\1\5\1\243\6\5\1\0"+
    "\2\5\7\0\2\5\2\0\6\5\2\0\1\56\3\5"+
    "\1\0\1\5\5\0\1\5\6\0\6\5\1\157\1\5"+
    "\1\0\2\5\2\0\10\5\1\0\2\5\7\0\2\5"+
    "\2\0\6\5\2\0\1\56\3\5\1\0\1\5\5\0"+
    "\1\5\6\0\5\5\1\244\2\5\1\0\2\5\2\0"+
    "\10\5\1\0\2\5\7\0\2\5\2\0\6\5\2\0"+
    "\1\56\3\5\1\0\1\5\5\0\1\5\6\0\10\5"+
    "\1\0\2\5\2\0\10\5\1\0\1\245\1\5\7\0"+
    "\2\5\2\0\6\5\2\0\1\56\3\5\1\0\1\5"+
    "\5\0\1\5\6\0\10\5\1\0\2\5\2\0\1\157"+
    "\7\5\1\0\2\5\7\0\2\5\2\0\6\5\2\0"+
    "\1\56\3\5\1\0\1\5\5\0\1\5\6\0\5\5"+
    "\1\246\2\5\1\0\2\5\2\0\10\5\1\0\2\5"+
    "\7\0\2\5\2\0\6\5\2\0\1\56\3\5\1\0"+
    "\1\5\5\0\1\5\6\0\7\5\1\247\1\0\2\5"+
    "\2\0\10\5\1\0\2\5\7\0\2\5\2\0\6\5"+
    "\2\0\1\56\3\5\1\0\1\5\5\0\1\5\6\0"+
    "\7\5\1\250\1\0\2\5\2\0\10\5\1\0\2\5"+
    "\7\0\2\5\2\0\6\5\2\0\1\56\3\5\1\0"+
    "\1\5\5\0\1\5\6\0\10\5\1\0\2\5\2\0"+
    "\10\5\1\0\1\175\1\5\7\0\2\5\2\0\6\5"+
    "\2\0\1\56\1\5\1\226\1\5\1\0\1\5\5\0"+
    "\1\5\6\0\10\5\1\0\2\5\2\0\10\5\1\0"+
    "\2\5\7\0\2\5\2\0\6\5\2\0\1\56\3\5"+
    "\1\0\1\5\5\0\1\5\6\0\10\5\1\0\2\5"+
    "\2\0\1\5\1\226\6\5\1\0\2\5\7\0\2\5"+
    "\2\0\6\5\2\0\1\56\3\5\1\0\1\5\5\0"+
    "\1\5\6\0\10\5\1\0\2\5\2\0\1\251\7\5"+
    "\1\0\2\5\7\0\2\5\60\0\1\252\55\0\1\253"+
    "\76\0\1\254\5\0\1\255\61\0\1\256\102\0\1\257"+
    "\73\0\1\211\60\0\1\260\103\0\1\261\102\0\1\262"+
    "\73\0\1\215\60\0\1\263\51\0\4\264\5\0\1\264"+
    "\1\0\1\264\20\0\1\264\2\0\1\264\5\0\1\264"+
    "\1\0\1\264\2\0\1\264\17\0\3\137\4\265\1\62"+
    "\1\0\3\137\1\265\1\137\1\265\20\137\1\265\2\137"+
    "\1\265\5\137\1\265\1\137\1\265\2\137\1\265\17\137"+
    "\66\0\1\266\7\0\6\5\2\0\1\56\3\5\1\0"+
    "\1\5\5\0\1\5\6\0\10\5\1\0\2\5\2\0"+
    "\5\5\1\226\2\5\1\0\2\5\7\0\2\5\1\0"+
    "\3\67\4\267\2\67\1\147\2\67\1\267\1\150\1\267"+
    "\20\67\1\267\2\67\1\267\5\67\1\267\1\67\1\267"+
    "\2\67\1\267\17\67\1\0\6\5\2\0\1\56\3\5"+
    "\1\0\1\5\5\0\1\5\6\0\10\5\1\0\2\5"+
    "\2\0\1\270\7\5\1\0\2\5\7\0\2\5\2\0"+
    "\6\5\2\0\1\56\3\5\1\0\1\5\5\0\1\5"+
    "\6\0\10\5\1\0\2\5\2\0\6\5\1\157\1\5"+
    "\1\0\2\5\7\0\2\5\57\0\1\271\17\0\6\5"+
    "\2\0\1\56\1\5\1\272\1\5\1\0\1\5\5\0"+
    "\1\5\6\0\10\5\1\0\2\5\2\0\10\5\1\0"+
    "\2\5\7\0\2\5\2\0\6\5\2\0\1\56\1\5"+
    "\1\273\1\5\1\0\1\5\5\0\1\5\6\0\10\5"+
    "\1\0\2\5\2\0\10\5\1\0\2\5\7\0\2\5"+
    "\57\0\1\274\17\0\6\5\2\0\1\56\3\5\1\0"+
    "\1\5\5\0\1\5\6\0\10\5\1\0\2\5\2\0"+
    "\1\275\7\5\1\0\2\5\7\0\2\5\2\0\6\5"+
    "\2\0\1\56\3\5\1\0\1\5\5\0\1\5\6\0"+
    "\10\5\1\0\2\5\2\0\6\5\1\276\1\5\1\0"+
    "\2\5\7\0\2\5\2\0\6\5\2\0\1\56\3\5"+
    "\1\0\1\5\5\0\1\5\6\0\7\5\1\277\1\0"+
    "\2\5\2\0\10\5\1\0\2\5\7\0\2\5\2\0"+
    "\6\5\2\0\1\56\3\5\1\0\1\5\5\0\1\5"+
    "\6\0\7\5\1\157\1\0\2\5\2\0\10\5\1\0"+
    "\2\5\7\0\2\5\2\0\6\5\2\0\1\56\3\5"+
    "\1\0\1\5\5\0\1\5\6\0\7\5\1\300\1\0"+
    "\2\5\2\0\10\5\1\0\2\5\7\0\2\5\2\0"+
    "\6\5\2\0\1\56\3\5\1\0\1\5\5\0\1\5"+
    "\6\0\3\5\1\157\4\5\1\0\2\5\2\0\10\5"+
    "\1\0\2\5\7\0\2\5\51\0\1\301\25\0\6\5"+
    "\2\0\1\56\3\5\1\0\1\5\5\0\1\302\6\0"+
    "\10\5\1\0\2\5\2\0\10\5\1\0\2\5\7\0"+
    "\2\5\2\0\6\5\2\0\1\56\3\5\1\0\1\5"+
    "\5\0\1\5\6\0\7\5\1\303\1\0\2\5\2\0"+
    "\10\5\1\0\2\5\7\0\2\5\2\0\6\5\2\0"+
    "\1\56\3\5\1\0\1\5\5\0\1\5\6\0\1\5"+
    "\1\175\6\5\1\0\2\5\2\0\10\5\1\0\2\5"+
    "\7\0\2\5\2\0\6\5\2\0\1\56\3\5\1\0"+
    "\1\5\5\0\1\5\6\0\10\5\1\0\2\5\2\0"+
    "\2\5\1\304\5\5\1\0\2\5\7\0\2\5\2\0"+
    "\6\5\2\0\1\56\1\5\1\305\1\5\1\0\1\5"+
    "\5\0\1\5\6\0\10\5\1\0\2\5\2\0\10\5"+
    "\1\0\2\5\7\0\2\5\2\0\6\5\2\0\1\56"+
    "\1\5\1\244\1\5\1\0\1\5\5\0\1\5\6\0"+
    "\10\5\1\0\2\5\2\0\10\5\1\0\2\5\7\0"+
    "\2\5\2\0\6\5\2\0\1\56\3\5\1\0\1\5"+
    "\5\0\1\5\6\0\10\5\1\0\2\5\2\0\1\5"+
    "\1\157\6\5\1\0\2\5\7\0\2\5\13\0\1\306"+
    "\121\0\1\307\50\0\1\310\121\0\1\310\72\0\1\211"+
    "\4\0\1\257\53\0\1\311\53\0\1\260\1\312\4\260"+
    "\1\312\2\0\3\260\1\0\1\260\1\0\1\312\1\0"+
    "\1\260\1\312\1\260\1\0\5\312\10\260\1\312\2\260"+
    "\2\0\10\260\1\0\2\260\1\312\1\0\1\312\1\0"+
    "\1\312\2\0\2\260\37\0\1\215\4\0\1\262\53\0"+
    "\1\313\53\0\1\263\1\314\4\263\1\314\2\0\3\263"+
    "\1\0\1\263\1\0\1\314\1\0\1\263\1\314\1\263"+
    "\1\0\5\314\10\263\1\314\2\263\2\0\10\263\1\0"+
    "\2\263\1\314\1\0\1\314\1\0\1\314\2\0\2\263"+
    "\4\0\4\315\5\0\1\315\1\0\1\315\20\0\1\315"+
    "\2\0\1\315\5\0\1\315\1\0\1\315\2\0\1\315"+
    "\17\0\3\137\4\316\1\62\1\0\3\137\1\316\1\137"+
    "\1\316\20\137\1\316\2\137\1\316\5\137\1\316\1\137"+
    "\1\316\2\137\1\316\17\137\3\67\4\317\2\67\1\147"+
    "\2\67\1\317\1\150\1\317\20\67\1\317\2\67\1\317"+
    "\5\67\1\317\1\67\1\317\2\67\1\317\17\67\1\0"+
    "\6\5\2\0\1\56\3\5\1\0\1\5\5\0\1\5"+
    "\6\0\10\5\1\0\2\5\2\0\1\5\1\320\6\5"+
    "\1\0\2\5\7\0\2\5\50\0\1\321\26\0\6\5"+
    "\2\0\1\56\3\5\1\0\1\5\5\0\1\5\6\0"+
    "\1\5\1\302\6\5\1\0\2\5\2\0\10\5\1\0"+
    "\2\5\7\0\2\5\2\0\6\5\2\0\1\56\3\5"+
    "\1\0\1\5\5\0\1\5\6\0\10\5\1\0\2\5"+
    "\2\0\10\5\1\0\1\5\1\175\7\0\2\5\2\0"+
    "\6\5\2\0\1\56\1\5\1\153\1\5\1\0\1\5"+
    "\5\0\1\5\6\0\10\5\1\0\2\5\2\0\10\5"+
    "\1\0\2\5\7\0\2\5\2\0\6\5\2\0\1\56"+
    "\3\5\1\0\1\5\5\0\1\5\6\0\3\5\1\322"+
    "\4\5\1\0\2\5\2\0\10\5\1\0\2\5\7\0"+
    "\2\5\2\0\6\5\2\0\1\56\3\5\1\0\1\5"+
    "\5\0\1\5\6\0\10\5\1\0\1\5\1\323\2\0"+
    "\10\5\1\0\2\5\7\0\2\5\2\0\6\5\2\0"+
    "\1\56\3\5\1\0\1\5\5\0\1\5\6\0\6\5"+
    "\1\324\1\5\1\0\2\5\2\0\10\5\1\0\2\5"+
    "\7\0\2\5\52\0\1\325\24\0\6\5\2\0\1\56"+
    "\3\5\1\0\1\5\5\0\1\5\6\0\10\5\1\0"+
    "\2\5\2\0\1\326\7\5\1\0\2\5\7\0\2\5"+
    "\2\0\6\5\2\0\1\56\3\5\1\0\1\5\5\0"+
    "\1\5\6\0\6\5\1\226\1\5\1\0\2\5\2\0"+
    "\10\5\1\0\2\5\7\0\2\5\2\0\6\5\2\0"+
    "\1\56\3\5\1\0\1\5\5\0\1\5\6\0\5\5"+
    "\1\327\2\5\1\0\2\5\2\0\10\5\1\0\2\5"+
    "\7\0\2\5\2\0\6\5\2\0\1\56\3\5\1\0"+
    "\1\5\5\0\1\5\6\0\10\5\1\0\2\5\2\0"+
    "\7\5\1\163\1\0\2\5\7\0\2\5\51\0\1\330"+
    "\66\0\1\331\110\0\1\332\40\0\1\260\74\0\1\263"+
    "\55\0\4\5\5\0\1\5\1\0\1\5\20\0\1\5"+
    "\2\0\1\5\5\0\1\5\1\0\1\5\2\0\1\5"+
    "\17\0\3\137\4\61\1\62\1\0\3\137\1\61\1\137"+
    "\1\61\20\137\1\61\2\137\1\61\5\137\1\61\1\137"+
    "\1\61\2\137\1\61\17\137\3\67\4\14\2\67\1\147"+
    "\2\67\1\14\1\150\1\14\20\67\1\14\2\67\1\14"+
    "\5\67\1\14\1\67\1\14\2\67\1\14\17\67\1\0"+
    "\6\5\2\0\1\56\3\5\1\0\1\5\5\0\1\5"+
    "\6\0\10\5\1\0\2\5\1\0\1\333\10\5\1\0"+
    "\2\5\7\0\2\5\37\0\1\334\37\0\6\5\2\0"+
    "\1\56\3\5\1\0\1\5\5\0\1\5\6\0\3\5"+
    "\1\335\4\5\1\0\2\5\2\0\10\5\1\0\2\5"+
    "\7\0\2\5\2\0\6\5\2\0\1\56\3\5\1\0"+
    "\1\5\5\0\1\5\6\0\7\5\1\251\1\0\2\5"+
    "\2\0\10\5\1\0\2\5\7\0\2\5\2\0\6\5"+
    "\2\0\1\56\3\5\1\0\1\5\5\0\1\5\6\0"+
    "\1\226\7\5\1\0\2\5\2\0\10\5\1\0\2\5"+
    "\7\0\2\5\51\0\1\336\25\0\6\5\2\0\1\56"+
    "\3\5\1\0\1\5\5\0\1\5\6\0\10\5\1\0"+
    "\2\5\2\0\1\5\1\337\6\5\1\0\2\5\7\0"+
    "\2\5\2\0\6\5\2\0\1\56\3\5\1\0\1\5"+
    "\5\0\1\5\6\0\10\5\1\0\2\5\2\0\2\5"+
    "\1\340\5\5\1\0\2\5\7\0\2\5\42\0\1\341"+
    "\104\0\1\342\74\0\1\343\100\0\1\344\1\0\1\345"+
    "\57\0\1\274\33\0\6\5\2\0\1\56\3\5\1\0"+
    "\1\5\5\0\1\5\6\0\10\5\1\0\2\5\2\0"+
    "\1\346\7\5\1\0\2\5\7\0\2\5\50\0\1\347"+
    "\26\0\6\5\2\0\1\56\3\5\1\0\1\5\5\0"+
    "\1\5\6\0\10\5\1\0\2\5\1\0\1\350\10\5"+
    "\1\0\2\5\7\0\2\5\2\0\6\5\2\0\1\56"+
    "\3\5\1\0\1\5\5\0\1\5\6\0\10\5\1\0"+
    "\2\5\2\0\6\5\1\351\1\5\1\0\2\5\7\0"+
    "\2\5\50\0\1\352\67\0\1\353\101\0\1\354\103\0"+
    "\1\355\67\0\1\356\24\0\6\5\2\0\1\56\3\5"+
    "\1\0\1\5\5\0\1\5\6\0\10\5\1\0\2\5"+
    "\2\0\1\5\1\357\6\5\1\0\2\5\7\0\2\5"+
    "\15\0\1\360\25\0\1\361\7\0\1\362\2\0\1\363"+
    "\54\0\1\364\40\0\6\5\2\0\1\56\3\5\1\0"+
    "\1\5\5\0\1\5\6\0\10\5\1\0\2\5\1\0"+
    "\1\365\10\5\1\0\2\5\7\0\2\5\51\0\1\17"+
    "\37\0\1\366\135\0\1\367\1\0\1\370\67\0\1\371"+
    "\101\0\1\372\17\0\6\5\2\0\1\56\3\5\1\0"+
    "\1\5\5\0\1\5\6\0\10\5\1\0\2\5\1\0"+
    "\1\373\10\5\1\0\2\5\7\0\2\5\51\0\1\374"+
    "\62\0\1\375\76\0\1\376\74\0\1\377\74\0\1\u0100"+
    "\71\0\1\u0101\73\0\1\u0102\52\0\1\u0103\74\0\1\u0104"+
    "\131\0\1\u0105\63\0\1\u0106\100\0\1\u0107\72\0\1\u0108"+
    "\110\0\1\u0109\71\0\1\u010a\76\0\1\u010b\34\0\1\u010c"+
    "\137\0\1\u010d\60\0\1\u010e\74\0\1\17\101\0\1\u010f"+
    "\62\0\1\u0110\75\0\1\u0111\111\0\1\274\45\0\1\u0112"+
    "\62\0\1\u0113\124\0\1\u0114\102\0\1\u0115\101\0\1\u0116"+
    "\70\0\1\17\72\0\1\u0117\65\0\1\205\104\0\1\u0118"+
    "\36\0\1\u0119\140\0\1\u0115\60\0\1\u011a\72\0\1\u011b"+
    "\103\0\1\373\67\0\1\u011c\104\0\1\u0103\73\0\1\u011d"+
    "\74\0\1\u011e\74\0\1\u011f\57\0\1\u010b\101\0\1\274"+
    "\103\0\1\274\74\0\1\371\76\0\1\u010b\22\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[16287];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\4\1\1\11\5\1\2\11\23\1\1\11"+
    "\5\1\1\11\3\1\1\0\3\1\1\11\1\0\1\1"+
    "\1\0\3\1\3\11\11\1\1\0\14\1\2\0\1\11"+
    "\11\0\2\1\1\11\4\1\1\0\2\1\1\11\16\1"+
    "\1\0\15\1\14\0\1\1\1\0\4\1\1\0\2\1"+
    "\1\0\6\1\1\0\10\1\6\0\1\1\2\0\1\1"+
    "\1\0\1\1\1\0\5\1\1\11\4\1\1\0\4\1"+
    "\10\0\3\1\1\0\3\1\1\0\2\1\5\0\4\1"+
    "\5\0\1\1\2\0\1\1\5\0\1\1\60\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[287];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */


	/**
	 * Constructor.  This must be here because JFlex does not generate a
	 * no-parameter constructor.
	 */
	public AuroraLogoSyntaxHighlighter() {
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 * @see #addToken(int, int, int)
	 */
	private void addHyperlinkToken(int start, int end, int tokenType) {
		int so = start + offsetShift;
		addToken(zzBuffer, start,end, tokenType, so, true);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 */
	private void addToken(int tokenType) {
		addToken(zzStartRead, zzMarkedPos-1, tokenType);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 * @see #addHyperlinkToken(int, int, int)
	 */
	private void addToken(int start, int end, int tokenType) {
		int so = start + offsetShift;
		addToken(zzBuffer, start,end, tokenType, so, false);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param array The character array.
	 * @param start The starting offset in the array.
	 * @param end The ending offset in the array.
	 * @param tokenType The token's type.
	 * @param startOffset The offset in the document at which this token
	 *        occurs.
	 * @param hyperlink Whether this token is a hyperlink.
	 */
	public void addToken(char[] array, int start, int end, int tokenType,
						int startOffset, boolean hyperlink) {
		super.addToken(array, start,end, tokenType, startOffset, hyperlink);
		zzStartRead = zzMarkedPos;
	}


	/**
	 * {@inheritDoc}
	 */
	public String[] getLineCommentStartAndEnd(int languageIndex) {
		return new String[] { "//", null };
	}


	/**
	 * Returns the first token in the linked list of tokens generated
	 * from <code>text</code>.  This method must be implemented by
	 * subclasses so they can correctly implement syntax highlighting.
	 *
	 * @param text The text from which to get tokens.
	 * @param initialTokenType The token type we should start with.
	 * @param startOffset The offset into the document at which
	 *        <code>text</code> starts.
	 * @return The first <code>Token</code> in a linked list representing
	 *         the syntax highlighted text.
	 */
	public Token getTokenList(Segment text, int initialTokenType, int startOffset) {

		resetTokenList();
		this.offsetShift = -text.offset + startOffset;

		// Start off in the proper state.
		int state = Token.NULL;
		switch (initialTokenType) {
						case Token.COMMENT_MULTILINE:
				state = MLC;
				start = text.offset;
				break;

			/* No documentation comments */
			default:
				state = Token.NULL;
		}

		s = text;
		try {
			yyreset(zzReader);
			yybegin(state);
			return yylex();
		} catch (IOException ioe) {
			ioe.printStackTrace();
			return new TokenImpl();
		}

	}


	/**
	 * Refills the input buffer.
	 *
	 * @return      <code>true</code> if EOF was reached, otherwise
	 *              <code>false</code>.
	 */
	private boolean zzRefill() {
		return zzCurrentPos>=s.offset+s.count;
	}


	/**
	 * Resets the scanner to read from a new input stream.
	 * Does not close the old reader.
	 *
	 * All internal variables are reset, the old input stream 
	 * <b>cannot</b> be reused (internal buffer is discarded and lost).
	 * Lexical state is set to <tt>YY_INITIAL</tt>.
	 *
	 * @param reader   the new input stream 
	 */
	public final void yyreset(Reader reader) {
		// 's' has been updated.
		zzBuffer = s.array;
		/*
		 * We replaced the line below with the two below it because zzRefill
		 * no longer "refills" the buffer (since the way we do it, it's always
		 * "full" the first time through, since it points to the segment's
		 * array).  So, we assign zzEndRead here.
		 */
		//zzStartRead = zzEndRead = s.offset;
		zzStartRead = s.offset;
		zzEndRead = zzStartRead + s.count - 1;
		zzCurrentPos = zzMarkedPos = zzPushbackPos = s.offset;
		zzLexicalState = YYINITIAL;
		zzReader = reader;
		zzAtBOL  = true;
		zzAtEOF  = false;
	}




  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AuroraLogoSyntaxHighlighter(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public AuroraLogoSyntaxHighlighter(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 174) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public org.fife.ui.rsyntaxtextarea.Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 4: 
          { addNullToken(); return firstToken;
          }
        case 25: break;
        case 20: 
          { addToken(Token.LITERAL_CHAR);
          }
        case 26: break;
        case 16: 
          { start = zzMarkedPos-2; yybegin(MLC);
          }
        case 27: break;
        case 6: 
          { addToken(Token.WHITESPACE);
          }
        case 28: break;
        case 19: 
          { addToken(Token.LITERAL_NUMBER_HEXADECIMAL);
          }
        case 29: break;
        case 21: 
          { addToken(Token.ERROR_STRING_DOUBLE);
          }
        case 30: break;
        case 17: 
          { addToken(Token.RESERVED_WORD);
          }
        case 31: break;
        case 8: 
          { addToken(Token.SEPARATOR);
          }
        case 32: break;
        case 1: 
          { addToken(Token.IDENTIFIER);
          }
        case 33: break;
        case 11: 
          { addToken(start,zzStartRead-1, Token.COMMENT_EOL); addNullToken(); return firstToken;
          }
        case 34: break;
        case 15: 
          { start = zzMarkedPos-2; yybegin(EOL_COMMENT);
          }
        case 35: break;
        case 22: 
          { addToken(Token.FUNCTION);
          }
        case 36: break;
        case 3: 
          { addToken(Token.ERROR_CHAR); addNullToken(); return firstToken;
          }
        case 37: break;
        case 5: 
          { addToken(Token.ERROR_STRING_DOUBLE); addNullToken(); return firstToken;
          }
        case 38: break;
        case 18: 
          { yybegin(YYINITIAL); addToken(start,zzStartRead+2-1, Token.COMMENT_MULTILINE);
          }
        case 39: break;
        case 13: 
          { addToken(Token.ERROR_CHAR);
          }
        case 40: break;
        case 14: 
          { addToken(Token.LITERAL_STRING_DOUBLE_QUOTE);
          }
        case 41: break;
        case 24: 
          { int temp=zzStartRead; addToken(start,zzStartRead-1, Token.COMMENT_EOL); addHyperlinkToken(temp,zzMarkedPos-1, Token.COMMENT_EOL); start = zzMarkedPos;
          }
        case 42: break;
        case 23: 
          { int temp=zzStartRead; addToken(start,zzStartRead-1, Token.COMMENT_MULTILINE); addHyperlinkToken(temp,zzMarkedPos-1, Token.COMMENT_MULTILINE); start = zzMarkedPos;
          }
        case 43: break;
        case 12: 
          { addToken(Token.ERROR_NUMBER_FORMAT);
          }
        case 44: break;
        case 2: 
          { addToken(Token.LITERAL_NUMBER_DECIMAL_INT);
          }
        case 45: break;
        case 7: 
          { addToken(Token.OPERATOR);
          }
        case 46: break;
        case 9: 
          { 
          }
        case 47: break;
        case 10: 
          { addToken(start,zzStartRead-1, Token.COMMENT_MULTILINE); return firstToken;
          }
        case 48: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            switch (zzLexicalState) {
            case EOL_COMMENT: {
              addToken(start,zzStartRead-1, Token.COMMENT_EOL); addNullToken(); return firstToken;
            }
            case 288: break;
            case YYINITIAL: {
              addNullToken(); return firstToken;
            }
            case 289: break;
            case MLC: {
              addToken(start,zzStartRead-1, Token.COMMENT_MULTILINE); return firstToken;
            }
            case 290: break;
            default:
            return null;
            }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
