/*
 * Copyright (C) 2022 Prof. Dr. David Buzatto
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package br.com.davidbuzatto.auroralogo.gui;

import java.awt.Color;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Scanner;
import javax.swing.AbstractAction;
import javax.swing.KeyStroke;

/**
 * Diálogo "Sobre".
 * 
 * @author Prof. Dr. David Buzatto
 */
public class DialogoSobre extends javax.swing.JDialog {

    private static String textoSobre;
    
    /**
     * Creates new form DialogoSobre
     */
    public DialogoSobre( Frame parent, boolean modal ) {
        
        super( parent, modal );
        initComponents();
        setBackground( new Color( 0, 0, 0, 0 ) );
        
        getRootPane().getInputMap().put( KeyStroke.getKeyStroke( KeyEvent.VK_ESCAPE, 0 ), "pararExecucao" );
        getRootPane().getActionMap().put( "pararExecucao", new AbstractAction() {
            @Override
            public void actionPerformed( ActionEvent e ) {
                dispose();
            }
        });
        
        getRootPane().addKeyListener( new KeyAdapter() {
            @Override
            public void keyPressed( KeyEvent e ) {
                dispose();
            }
        });
        
        getRootPane().addFocusListener( new FocusAdapter() {
            @Override
            public void focusLost( FocusEvent e ) {
                dispose();
            }
        });
        
        if ( textoSobre == null ) {
            Scanner s = new Scanner( getClass().getResourceAsStream( "/br/com/davidbuzatto/auroralogo/ajuda/textoSobre.txt" ) );
            String texto = "";
            while ( s.hasNextLine() ) {
                texto += s.nextLine() + "<br/>";
            }
            textoSobre = texto.trim();
            textoSobre = textoSobre.substring( 0, textoSobre.lastIndexOf( "<br/>" ) );
        }
        
        lblSobre.setText( "<html><body>" + textoSobre + "</html></body>" );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelSobre = new br.com.davidbuzatto.auroralogo.gui.PainelSobre();
        lblSobre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sobre...");
        setUndecorated(true);
        setResizable(false);

        lblSobre.setForeground(new java.awt.Color(0, 51, 102));
        lblSobre.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSobre.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout painelSobreLayout = new javax.swing.GroupLayout(painelSobre);
        painelSobre.setLayout(painelSobreLayout);
        painelSobreLayout.setHorizontalGroup(
            painelSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSobreLayout.createSequentialGroup()
                .addContainerGap(179, Short.MAX_VALUE)
                .addComponent(lblSobre, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        painelSobreLayout.setVerticalGroup(
            painelSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSobreLayout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addComponent(lblSobre, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelSobre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelSobre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblSobre;
    private br.com.davidbuzatto.auroralogo.gui.PainelSobre painelSobre;
    // End of variables declaration//GEN-END:variables
}
