/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.davidbuzatto.auroralogo.gui;

import br.com.davidbuzatto.auroralogo.parser.AuroraLogoLexer;
import br.com.davidbuzatto.auroralogo.parser.AuroraLogoParser;
import br.com.davidbuzatto.auroralogo.parser.impl.DesenhistaAuroraLogoVisitor;
import br.com.davidbuzatto.auroralogo.utils.Utils;
import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.Scanner;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.RecognitionException;
import org.antlr.v4.runtime.tree.ParseTree;
import org.fife.ui.rsyntaxtextarea.AbstractTokenMakerFactory;
import org.fife.ui.rsyntaxtextarea.ErrorStrip;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextAreaEditorKit;
import org.fife.ui.rsyntaxtextarea.Style;
import org.fife.ui.rsyntaxtextarea.SyntaxScheme;
import org.fife.ui.rsyntaxtextarea.Theme;
import org.fife.ui.rsyntaxtextarea.TokenMakerFactory;
import org.fife.ui.rtextarea.RTextScrollPane;

/**
 *
 * @author David
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    private static final String VERSAO = "v0.1";
    private static final boolean PRODUCAO = false;
    
    private RSyntaxTextArea textAreaCodigo;
    private RTextScrollPane scrollPaneCodigo;
    private Font fontePadrao;
    
    private Tartaruga tartaruga;
    
    private File arquivoAtual;
    private FileNameExtensionFilter filtroExtensao;

    private boolean pararPassoAPassoAutomatico;
    
    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {

        initComponents();
        prepararTextArea();
        montarTitulo( true );
        atualizarBotoesDesfazerRefazer( textAreaCodigo );
        atualizarQuadrosPorSegundo();
        fontePadrao = textAreaCodigo.getDefaultFont();
        
        filtroExtensao = new FileNameExtensionFilter( 
                "Arquivo AuroraLogo" , "aulg" );
        
        //setExtendedState( MAXIMIZED_BOTH );
        
        tartaruga = new Tartaruga( 
                painelDesenho.getWidth() / 2, 
                painelDesenho.getHeight() / 2, 
                0, 1, 
                Color.BLACK, 
                true, 
                painelDesenho );
        painelDesenho.setTartaruga( tartaruga );
        
        /*tartaruga.moverParaCima( 10 );
        tartaruga.moverParaDireita( 50 );
        tartaruga.trocarCor( Color.decode( "#ff0000" ) );
        tartaruga.moverParaBaixo( 100 );
        tartaruga.moverParaEsquerda( 40 );*/
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupTemas = new javax.swing.ButtonGroup();
        painelCodigo = new javax.swing.JPanel();
        painelDesenho = new br.com.davidbuzatto.auroralogo.gui.PainelDesenho();
        barraFerramentas = new javax.swing.JToolBar();
        btnNovo = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnSalvarComo = new javax.swing.JButton();
        separador1 = new javax.swing.JToolBar.Separator();
        btnDesfazer = new javax.swing.JButton();
        btnRefazer = new javax.swing.JButton();
        separador2 = new javax.swing.JToolBar.Separator();
        btnAumentarFonte = new javax.swing.JButton();
        btnDiminuirFonte = new javax.swing.JButton();
        separador3 = new javax.swing.JToolBar.Separator();
        btnExecutar = new javax.swing.JButton();
        separador4 = new javax.swing.JToolBar.Separator();
        btnExecutarPassoAPasso = new javax.swing.JButton();
        btnPararPassoAPasso = new javax.swing.JButton();
        btnInicioPassoAPasso = new javax.swing.JButton();
        btnAnteriorPassoAPasso = new javax.swing.JButton();
        btnProximoPassoAPasso = new javax.swing.JButton();
        btnUltimoPassoAPasso = new javax.swing.JButton();
        separador5 = new javax.swing.JToolBar.Separator();
        btnExecutarPassoAPassoAutomatico = new javax.swing.JButton();
        btnPararExecutarPassoAutomatico = new javax.swing.JButton();
        sliderQuadrosPorSegundo = new javax.swing.JSlider();
        lblQuadrosPorSegundo = new javax.swing.JLabel();
        preenchimento = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        btnDepurador = new javax.swing.JToggleButton();
        barraMenu = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuItemNovo = new javax.swing.JMenuItem();
        menuItemAbrir = new javax.swing.JMenuItem();
        menuItemSalvar = new javax.swing.JMenuItem();
        menuItemSalvarComo = new javax.swing.JMenuItem();
        separadorMenuArquivo1 = new javax.swing.JPopupMenu.Separator();
        menuSair = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenu();
        menuItemDesfazer = new javax.swing.JMenuItem();
        menuItemRefazer = new javax.swing.JMenuItem();
        separadorMenuEditar1 = new javax.swing.JPopupMenu.Separator();
        menuItemRecortar = new javax.swing.JMenuItem();
        menuItemCopiar = new javax.swing.JMenuItem();
        menuItemColar = new javax.swing.JMenuItem();
        separadorMenuEditar2 = new javax.swing.JPopupMenu.Separator();
        menuItemCopiarTextoFormatado = new javax.swing.JMenuItem();
        separadorMenuEditar3 = new javax.swing.JPopupMenu.Separator();
        menuItemAumentarFonte = new javax.swing.JMenuItem();
        menuItemDiminuirFonte = new javax.swing.JMenuItem();
        menuExecutar = new javax.swing.JMenu();
        menuItemExecutar = new javax.swing.JMenuItem();
        menuItemExecutarPassoAPasso = new javax.swing.JMenuItem();
        menuItemExecutarPassoAPassoAutomatico = new javax.swing.JMenuItem();
        separadorMenuExecutar1 = new javax.swing.JPopupMenu.Separator();
        menuItemCBDepurador = new javax.swing.JCheckBoxMenuItem();
        menuExemplos = new javax.swing.JMenu();
        submenuTemas = new javax.swing.JMenu();
        menuItemRTemaClaro = new javax.swing.JRadioButtonMenuItem();
        menuItemRTemaEscuro = new javax.swing.JRadioButtonMenuItem();
        menuAjuda = new javax.swing.JMenu();
        menuItemConfiguracoes1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("AuroraLogo");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        painelCodigo.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout painelDesenhoLayout = new javax.swing.GroupLayout(painelDesenho);
        painelDesenho.setLayout(painelDesenhoLayout);
        painelDesenhoLayout.setHorizontalGroup(
            painelDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );
        painelDesenhoLayout.setVerticalGroup(
            painelDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/auroralogo/gui/icones/page_white_add.png"))); // NOI18N
        btnNovo.setToolTipText("Novo");
        btnNovo.setFocusable(false);
        btnNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        barraFerramentas.add(btnNovo);

        btnAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/auroralogo/gui/icones/folder.png"))); // NOI18N
        btnAbrir.setToolTipText("Abrir");
        btnAbrir.setFocusable(false);
        btnAbrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });
        barraFerramentas.add(btnAbrir);

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/auroralogo/gui/icones/disk.png"))); // NOI18N
        btnSalvar.setToolTipText("Salvar");
        btnSalvar.setFocusable(false);
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        barraFerramentas.add(btnSalvar);

        btnSalvarComo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/auroralogo/gui/icones/disk_multiple.png"))); // NOI18N
        btnSalvarComo.setToolTipText("Salvar Como");
        btnSalvarComo.setFocusable(false);
        btnSalvarComo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvarComo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalvarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarComoActionPerformed(evt);
            }
        });
        barraFerramentas.add(btnSalvarComo);
        barraFerramentas.add(separador1);

        btnDesfazer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/auroralogo/gui/icones/arrow_undo.png"))); // NOI18N
        btnDesfazer.setToolTipText("Desfazer");
        btnDesfazer.setFocusable(false);
        btnDesfazer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDesfazer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDesfazer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesfazerActionPerformed(evt);
            }
        });
        barraFerramentas.add(btnDesfazer);

        btnRefazer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/auroralogo/gui/icones/arrow_redo.png"))); // NOI18N
        btnRefazer.setToolTipText("Salvar Como");
        btnRefazer.setFocusable(false);
        btnRefazer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRefazer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRefazer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefazerActionPerformed(evt);
            }
        });
        barraFerramentas.add(btnRefazer);
        barraFerramentas.add(separador2);

        btnAumentarFonte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/auroralogo/gui/icones/font_add.png"))); // NOI18N
        btnAumentarFonte.setToolTipText("Aumentar Fonte");
        btnAumentarFonte.setFocusable(false);
        btnAumentarFonte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAumentarFonte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAumentarFonte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAumentarFonteActionPerformed(evt);
            }
        });
        barraFerramentas.add(btnAumentarFonte);

        btnDiminuirFonte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/auroralogo/gui/icones/font_delete.png"))); // NOI18N
        btnDiminuirFonte.setToolTipText("Diminuir Fonte");
        btnDiminuirFonte.setFocusable(false);
        btnDiminuirFonte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDiminuirFonte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDiminuirFonte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiminuirFonteActionPerformed(evt);
            }
        });
        barraFerramentas.add(btnDiminuirFonte);
        barraFerramentas.add(separador3);

        btnExecutar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/auroralogo/gui/icones/script_go.png"))); // NOI18N
        btnExecutar.setToolTipText("Executar");
        btnExecutar.setFocusable(false);
        btnExecutar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExecutar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecutarActionPerformed(evt);
            }
        });
        barraFerramentas.add(btnExecutar);
        barraFerramentas.add(separador4);

        btnExecutarPassoAPasso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/auroralogo/gui/icones/script_lightning.png"))); // NOI18N
        btnExecutarPassoAPasso.setToolTipText("Executar Passo a Passo");
        btnExecutarPassoAPasso.setFocusable(false);
        btnExecutarPassoAPasso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExecutarPassoAPasso.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExecutarPassoAPasso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecutarPassoAPassoActionPerformed(evt);
            }
        });
        barraFerramentas.add(btnExecutarPassoAPasso);

        btnPararPassoAPasso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/auroralogo/gui/icones/control_stop_blue.png"))); // NOI18N
        btnPararPassoAPasso.setToolTipText("Parar Execução Passo a Passo");
        btnPararPassoAPasso.setEnabled(false);
        btnPararPassoAPasso.setFocusable(false);
        btnPararPassoAPasso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPararPassoAPasso.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPararPassoAPasso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPararPassoAPassoActionPerformed(evt);
            }
        });
        barraFerramentas.add(btnPararPassoAPasso);

        btnInicioPassoAPasso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/auroralogo/gui/icones/control_start_blue.png"))); // NOI18N
        btnInicioPassoAPasso.setToolTipText("Início");
        btnInicioPassoAPasso.setEnabled(false);
        btnInicioPassoAPasso.setFocusable(false);
        btnInicioPassoAPasso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInicioPassoAPasso.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnInicioPassoAPasso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioPassoAPassoActionPerformed(evt);
            }
        });
        barraFerramentas.add(btnInicioPassoAPasso);

        btnAnteriorPassoAPasso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/auroralogo/gui/icones/control_rewind_blue.png"))); // NOI18N
        btnAnteriorPassoAPasso.setToolTipText("Anterior");
        btnAnteriorPassoAPasso.setEnabled(false);
        btnAnteriorPassoAPasso.setFocusable(false);
        btnAnteriorPassoAPasso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAnteriorPassoAPasso.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAnteriorPassoAPasso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorPassoAPassoActionPerformed(evt);
            }
        });
        barraFerramentas.add(btnAnteriorPassoAPasso);

        btnProximoPassoAPasso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/auroralogo/gui/icones/control_fastforward_blue.png"))); // NOI18N
        btnProximoPassoAPasso.setToolTipText("Próximo");
        btnProximoPassoAPasso.setEnabled(false);
        btnProximoPassoAPasso.setFocusable(false);
        btnProximoPassoAPasso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProximoPassoAPasso.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProximoPassoAPasso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoPassoAPassoActionPerformed(evt);
            }
        });
        barraFerramentas.add(btnProximoPassoAPasso);

        btnUltimoPassoAPasso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/auroralogo/gui/icones/control_end_blue.png"))); // NOI18N
        btnUltimoPassoAPasso.setToolTipText("Último");
        btnUltimoPassoAPasso.setEnabled(false);
        btnUltimoPassoAPasso.setFocusable(false);
        btnUltimoPassoAPasso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUltimoPassoAPasso.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUltimoPassoAPasso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoPassoAPassoActionPerformed(evt);
            }
        });
        barraFerramentas.add(btnUltimoPassoAPasso);
        barraFerramentas.add(separador5);

        btnExecutarPassoAPassoAutomatico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/auroralogo/gui/icones/clock_go.png"))); // NOI18N
        btnExecutarPassoAPassoAutomatico.setToolTipText("Executar Passo a Passo Automático");
        btnExecutarPassoAPassoAutomatico.setFocusable(false);
        btnExecutarPassoAPassoAutomatico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExecutarPassoAPassoAutomatico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExecutarPassoAPassoAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecutarPassoAPassoAutomaticoActionPerformed(evt);
            }
        });
        barraFerramentas.add(btnExecutarPassoAPassoAutomatico);

        btnPararExecutarPassoAutomatico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/auroralogo/gui/icones/control_stop_blue.png"))); // NOI18N
        btnPararExecutarPassoAutomatico.setToolTipText("Parar Execução Passo a Passo Automático");
        btnPararExecutarPassoAutomatico.setEnabled(false);
        btnPararExecutarPassoAutomatico.setFocusable(false);
        btnPararExecutarPassoAutomatico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPararExecutarPassoAutomatico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPararExecutarPassoAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPararExecutarPassoAutomaticoActionPerformed(evt);
            }
        });
        barraFerramentas.add(btnPararExecutarPassoAutomatico);

        sliderQuadrosPorSegundo.setMajorTickSpacing(5);
        sliderQuadrosPorSegundo.setMaximum(300);
        sliderQuadrosPorSegundo.setMinimum(5);
        sliderQuadrosPorSegundo.setMinorTickSpacing(5);
        sliderQuadrosPorSegundo.setSnapToTicks(true);
        sliderQuadrosPorSegundo.setToolTipText("Velocidade Passo a Passo");
        sliderQuadrosPorSegundo.setValue(100);
        sliderQuadrosPorSegundo.setMaximumSize(new java.awt.Dimension(150, 20));
        sliderQuadrosPorSegundo.setMinimumSize(new java.awt.Dimension(150, 20));
        sliderQuadrosPorSegundo.setPreferredSize(new java.awt.Dimension(150, 20));
        sliderQuadrosPorSegundo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderQuadrosPorSegundoStateChanged(evt);
            }
        });
        barraFerramentas.add(sliderQuadrosPorSegundo);

        lblQuadrosPorSegundo.setText("quadros por segundo");
        lblQuadrosPorSegundo.setMaximumSize(new java.awt.Dimension(150, 16));
        lblQuadrosPorSegundo.setMinimumSize(new java.awt.Dimension(150, 16));
        lblQuadrosPorSegundo.setPreferredSize(new java.awt.Dimension(150, 16));
        barraFerramentas.add(lblQuadrosPorSegundo);
        barraFerramentas.add(preenchimento);

        btnDepurador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/auroralogo/gui/icones/bug.png"))); // NOI18N
        btnDepurador.setToolTipText("Depurador");
        btnDepurador.setFocusable(false);
        btnDepurador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDepurador.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDepurador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepuradorActionPerformed(evt);
            }
        });
        barraFerramentas.add(btnDepurador);

        menuArquivo.setText("Arquivo");

        menuItemNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/auroralogo/gui/icones/page_white_add.png"))); // NOI18N
        menuItemNovo.setText("Novo");
        menuItemNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNovoActionPerformed(evt);
            }
        });
        menuArquivo.add(menuItemNovo);

        menuItemAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/auroralogo/gui/icones/folder.png"))); // NOI18N
        menuItemAbrir.setText("Abrir");
        menuItemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAbrirActionPerformed(evt);
            }
        });
        menuArquivo.add(menuItemAbrir);

        menuItemSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/auroralogo/gui/icones/disk.png"))); // NOI18N
        menuItemSalvar.setText("Salvar");
        menuItemSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalvarActionPerformed(evt);
            }
        });
        menuArquivo.add(menuItemSalvar);

        menuItemSalvarComo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/auroralogo/gui/icones/disk_multiple.png"))); // NOI18N
        menuItemSalvarComo.setText("Salvar Como");
        menuItemSalvarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalvarComoActionPerformed(evt);
            }
        });
        menuArquivo.add(menuItemSalvarComo);
        menuArquivo.add(separadorMenuArquivo1);

        menuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/auroralogo/gui/icones/door_out.png"))); // NOI18N
        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        menuArquivo.add(menuSair);

        barraMenu.add(menuArquivo);

        menuEditar.setText("Editar");

        menuItemDesfazer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/auroralogo/gui/icones/arrow_undo.png"))); // NOI18N
        menuItemDesfazer.setText("Defazer");
        menuItemDesfazer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDesfazerActionPerformed(evt);
            }
        });
        menuEditar.add(menuItemDesfazer);

        menuItemRefazer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/auroralogo/gui/icones/arrow_redo.png"))); // NOI18N
        menuItemRefazer.setText("Refazer");
        menuItemRefazer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRefazerActionPerformed(evt);
            }
        });
        menuEditar.add(menuItemRefazer);
        menuEditar.add(separadorMenuEditar1);

        menuItemRecortar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/auroralogo/gui/icones/cut_red.png"))); // NOI18N
        menuItemRecortar.setText("Recortar");
        menuItemRecortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRecortarActionPerformed(evt);
            }
        });
        menuEditar.add(menuItemRecortar);

        menuItemCopiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/auroralogo/gui/icones/page_white_copy.png"))); // NOI18N
        menuItemCopiar.setText("Copiar");
        menuItemCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCopiarActionPerformed(evt);
            }
        });
        menuEditar.add(menuItemCopiar);

        menuItemColar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/auroralogo/gui/icones/page_white_paste.png"))); // NOI18N
        menuItemColar.setText("Colar");
        menuItemColar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemColarActionPerformed(evt);
            }
        });
        menuEditar.add(menuItemColar);
        menuEditar.add(separadorMenuEditar2);

        menuItemCopiarTextoFormatado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/auroralogo/gui/icones/page_word.png"))); // NOI18N
        menuItemCopiarTextoFormatado.setText("Copiar Texto Formatado");
        menuItemCopiarTextoFormatado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCopiarTextoFormatadoActionPerformed(evt);
            }
        });
        menuEditar.add(menuItemCopiarTextoFormatado);
        menuEditar.add(separadorMenuEditar3);

        menuItemAumentarFonte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/auroralogo/gui/icones/font_add.png"))); // NOI18N
        menuItemAumentarFonte.setText("Aumentar Fonte");
        menuItemAumentarFonte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAumentarFonteActionPerformed(evt);
            }
        });
        menuEditar.add(menuItemAumentarFonte);

        menuItemDiminuirFonte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/auroralogo/gui/icones/font_delete.png"))); // NOI18N
        menuItemDiminuirFonte.setText("Diminuir Fonte");
        menuItemDiminuirFonte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDiminuirFonteActionPerformed(evt);
            }
        });
        menuEditar.add(menuItemDiminuirFonte);

        barraMenu.add(menuEditar);

        menuExecutar.setText("Executar");

        menuItemExecutar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/auroralogo/gui/icones/script_go.png"))); // NOI18N
        menuItemExecutar.setText("Executar");
        menuItemExecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExecutarActionPerformed(evt);
            }
        });
        menuExecutar.add(menuItemExecutar);

        menuItemExecutarPassoAPasso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/auroralogo/gui/icones/script_lightning.png"))); // NOI18N
        menuItemExecutarPassoAPasso.setText("Executar Passo a Passo");
        menuItemExecutarPassoAPasso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExecutarPassoAPassoActionPerformed(evt);
            }
        });
        menuExecutar.add(menuItemExecutarPassoAPasso);

        menuItemExecutarPassoAPassoAutomatico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/auroralogo/gui/icones/clock_go.png"))); // NOI18N
        menuItemExecutarPassoAPassoAutomatico.setText("Executar Passo a Passo (Automático)");
        menuItemExecutarPassoAPassoAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExecutarPassoAPassoAutomaticoActionPerformed(evt);
            }
        });
        menuExecutar.add(menuItemExecutarPassoAPassoAutomatico);
        menuExecutar.add(separadorMenuExecutar1);

        menuItemCBDepurador.setText("Ativar Depurador");
        menuItemCBDepurador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/auroralogo/gui/icones/bug.png"))); // NOI18N
        menuItemCBDepurador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCBDepuradorActionPerformed(evt);
            }
        });
        menuExecutar.add(menuItemCBDepurador);

        barraMenu.add(menuExecutar);

        menuExemplos.setText("Exemplos");
        barraMenu.add(menuExemplos);

        submenuTemas.setText("Temas");

        btnGroupTemas.add(menuItemRTemaClaro);
        menuItemRTemaClaro.setSelected(true);
        menuItemRTemaClaro.setText("Claro");
        menuItemRTemaClaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRTemaClaroActionPerformed(evt);
            }
        });
        submenuTemas.add(menuItemRTemaClaro);

        btnGroupTemas.add(menuItemRTemaEscuro);
        menuItemRTemaEscuro.setText("Escuro");
        menuItemRTemaEscuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRTemaEscuroActionPerformed(evt);
            }
        });
        submenuTemas.add(menuItemRTemaEscuro);

        barraMenu.add(submenuTemas);

        menuAjuda.setText("Ajuda");

        menuItemConfiguracoes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/auroralogo/gui/icones/help.png"))); // NOI18N
        menuItemConfiguracoes1.setText("Sobre...");
        menuItemConfiguracoes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConfiguracoes1ActionPerformed(evt);
            }
        });
        menuAjuda.add(menuItemConfiguracoes1);

        barraMenu.add(menuAjuda);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDesenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(barraFerramentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(barraFerramentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
                    .addComponent(painelDesenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        novoArquivo();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        abrirArquivo();
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        salvarArquivo();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecutarActionPerformed
        executar();
    }//GEN-LAST:event_btnExecutarActionPerformed

    private void btnExecutarPassoAPassoAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecutarPassoAPassoAutomaticoActionPerformed
        executarPassoAPassoAutomatico();
    }//GEN-LAST:event_btnExecutarPassoAPassoAutomaticoActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        
        tartaruga.atualizarPosicaoEstadoInicial( painelDesenho.getWidth() / 2, painelDesenho.getHeight() / 2 );
        
        if ( !tartaruga.estadoInicial() ) {
            executarCodigo();
        }
        
        painelCodigo.repaint();
        
    }//GEN-LAST:event_formComponentResized

    private void btnSalvarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarComoActionPerformed
        salvarArquivoComo();
    }//GEN-LAST:event_btnSalvarComoActionPerformed

    private void menuItemNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNovoActionPerformed
        novoArquivo();
    }//GEN-LAST:event_menuItemNovoActionPerformed

    private void menuItemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAbrirActionPerformed
        abrirArquivo();
    }//GEN-LAST:event_menuItemAbrirActionPerformed

    private void menuItemSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalvarActionPerformed
        salvarArquivo();
    }//GEN-LAST:event_menuItemSalvarActionPerformed

    private void menuItemSalvarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalvarComoActionPerformed
        salvarArquivoComo();
    }//GEN-LAST:event_menuItemSalvarComoActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        sair();
    }//GEN-LAST:event_menuSairActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        sair();
    }//GEN-LAST:event_formWindowClosing

    private void btnDesfazerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesfazerActionPerformed
        desfazer();
    }//GEN-LAST:event_btnDesfazerActionPerformed

    private void btnRefazerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefazerActionPerformed
        refazer();
    }//GEN-LAST:event_btnRefazerActionPerformed

    private void btnPararExecutarPassoAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPararExecutarPassoAutomaticoActionPerformed
        pararPassoAPassoAutomatico = true;
    }//GEN-LAST:event_btnPararExecutarPassoAutomaticoActionPerformed

    private void btnInicioPassoAPassoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioPassoAPassoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioPassoAPassoActionPerformed

    private void btnAnteriorPassoAPassoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorPassoAPassoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnteriorPassoAPassoActionPerformed

    private void btnProximoPassoAPassoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoPassoAPassoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProximoPassoAPassoActionPerformed

    private void btnUltimoPassoAPassoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoPassoAPassoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUltimoPassoAPassoActionPerformed

    private void btnExecutarPassoAPassoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecutarPassoAPassoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExecutarPassoAPassoActionPerformed

    private void btnPararPassoAPassoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPararPassoAPassoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPararPassoAPassoActionPerformed

    private void menuItemDesfazerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDesfazerActionPerformed
        desfazer();
    }//GEN-LAST:event_menuItemDesfazerActionPerformed

    private void menuItemRefazerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRefazerActionPerformed
        refazer();
    }//GEN-LAST:event_menuItemRefazerActionPerformed

    private void menuItemRecortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRecortarActionPerformed
        textAreaCodigo.cut();
    }//GEN-LAST:event_menuItemRecortarActionPerformed

    private void menuItemCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCopiarActionPerformed
        textAreaCodigo.copy();
    }//GEN-LAST:event_menuItemCopiarActionPerformed

    private void menuItemColarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemColarActionPerformed
        textAreaCodigo.paste();
    }//GEN-LAST:event_menuItemColarActionPerformed

    private void menuItemCopiarTextoFormatadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCopiarTextoFormatadoActionPerformed
        textAreaCodigo.copyAsStyledText();
    }//GEN-LAST:event_menuItemCopiarTextoFormatadoActionPerformed

    private void menuItemAumentarFonteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAumentarFonteActionPerformed
        aumentarFonte( evt );
    }//GEN-LAST:event_menuItemAumentarFonteActionPerformed

    private void menuItemDiminuirFonteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDiminuirFonteActionPerformed
        diminuirFonte();
    }//GEN-LAST:event_menuItemDiminuirFonteActionPerformed

    private void menuItemExecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExecutarActionPerformed
        executar();
    }//GEN-LAST:event_menuItemExecutarActionPerformed

    private void menuItemExecutarPassoAPassoAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExecutarPassoAPassoAutomaticoActionPerformed
        executarPassoAPassoAutomatico();
    }//GEN-LAST:event_menuItemExecutarPassoAPassoAutomaticoActionPerformed

    private void menuItemExecutarPassoAPassoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExecutarPassoAPassoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemExecutarPassoAPassoActionPerformed

    private void menuItemConfiguracoes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConfiguracoes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemConfiguracoes1ActionPerformed

    private void btnDiminuirFonteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiminuirFonteActionPerformed
        diminuirFonte();
    }//GEN-LAST:event_btnDiminuirFonteActionPerformed

    private void btnAumentarFonteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAumentarFonteActionPerformed
        aumentarFonte( evt );
    }//GEN-LAST:event_btnAumentarFonteActionPerformed

    private void btnDepuradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepuradorActionPerformed
        tartaruga.setDepuradorAtivo( !tartaruga.isDepuradorAtivo() );
        menuItemCBDepurador.setSelected( tartaruga.isDepuradorAtivo() );
        menuItemCBDepurador.setText( tartaruga.isDepuradorAtivo() ? "Desativar Depurador" : "Ativar Depurador" );
        painelDesenho.repaint();
    }//GEN-LAST:event_btnDepuradorActionPerformed

    private void menuItemCBDepuradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCBDepuradorActionPerformed
        tartaruga.setDepuradorAtivo( !tartaruga.isDepuradorAtivo() );
        btnDepurador.setSelected( tartaruga.isDepuradorAtivo() );
        menuItemCBDepurador.setText( tartaruga.isDepuradorAtivo() ? "Desativar Depurador" : "Ativar Depurador" );
        painelDesenho.repaint();
    }//GEN-LAST:event_menuItemCBDepuradorActionPerformed

    private void sliderQuadrosPorSegundoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderQuadrosPorSegundoStateChanged
        atualizarQuadrosPorSegundo();
    }//GEN-LAST:event_sliderQuadrosPorSegundoStateChanged

    private void menuItemRTemaClaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRTemaClaroActionPerformed
        FlatIntelliJLaf.setup();
        SwingUtilities.updateComponentTreeUI( this );
        configurarTemaTextAreaCodigoClaro();
    }//GEN-LAST:event_menuItemRTemaClaroActionPerformed

    private void menuItemRTemaEscuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRTemaEscuroActionPerformed
        FlatDarculaLaf.setup();
        SwingUtilities.updateComponentTreeUI( this );
        configurarTemaTextAreaCodigoEscuro();
    }//GEN-LAST:event_menuItemRTemaEscuroActionPerformed

    private void atualizarQuadrosPorSegundo() {
        lblQuadrosPorSegundo.setText( 
                String.format( " %d quadros por segundo", 
                sliderQuadrosPorSegundo.getValue() ) );
    }
    
    private void montarTitulo( boolean inserirAsterisco ) {
        
        setTitle( "AuroraLogo - " + VERSAO );
        
        if ( arquivoAtual != null ) {
            setTitle( getTitle() + " - " + arquivoAtual.getName() );
        } else {
            setTitle( getTitle() + " - " + "Sem título" );
        }
        
        if ( inserirAsterisco ) {
            setTitle( getTitle() + "*" );
        }
        
    }
    
    private void prepararTextArea() {

        textAreaCodigo = criarTextAreaCodigo();
        
        AbstractTokenMakerFactory atmf = (AbstractTokenMakerFactory) TokenMakerFactory.getDefaultInstance();
        atmf.putMapping( "text/AuroraLogo", "br.com.davidbuzatto.auroralogo.gui.sh.AuroraLogoSyntaxHighlighter");
        textAreaCodigo.setSyntaxEditingStyle( "text/AuroraLogo" );

        /*SyntaxScheme syntaxScheme = new SyntaxScheme( true );
        syntaxScheme.setStyle( SyntaxScheme.RESERVED_WORD, new Style( new Color( Utils.getIntPref( "RESERVED_WORD" ) ) ) );
        syntaxScheme.setStyle( SyntaxScheme.RESERVED_WORD_2, new Style( new Color( Utils.getIntPref( "RESERVED_WORD_2" ) ) ) );
        syntaxScheme.setStyle( SyntaxScheme.IDENTIFIER, new Style( Color.GREEN.darker() ) );
        syntaxScheme.setStyle( SyntaxScheme.OPERATOR, new Style( Color.decode( "#9e6d03" ) ) );
        syntaxScheme.setStyle( SyntaxScheme.FUNCTION, new Style( new Color( Utils.getIntPref( "FUNCTION" ) ) ) );
        syntaxScheme.setStyle( SyntaxScheme.LITERAL_NUMBER_DECIMAL_INT, new Style( Color.MAGENTA.darker().darker() ) );
        syntaxScheme.setStyle( SyntaxScheme.LITERAL_NUMBER_FLOAT, new Style( Color.MAGENTA.darker().darker() ) );
        syntaxScheme.setStyle( SyntaxScheme.LITERAL_NUMBER_HEXADECIMAL, new Style( Color.MAGENTA.darker().darker() ) );
        syntaxScheme.setStyle( SyntaxScheme.COMMENT_EOL, new Style( Color.GRAY ) );
        syntaxScheme.setStyle( SyntaxScheme.COMMENT_MULTILINE, new Style( Color.GRAY.darker() ) );
        syntaxScheme.setStyle( SyntaxScheme.COMMENT_DOCUMENTATION, new Style( Color.BLUE.darker().darker() ) );
        textAreaCodigo.setSyntaxScheme( syntaxScheme );*/
        
        configurarTemaTextAreaCodigoClaro();
        
        scrollPaneCodigo = new RTextScrollPane( textAreaCodigo, true );
        ErrorStrip errorStrip = new ErrorStrip( textAreaCodigo );
        
        painelCodigo.add( scrollPaneCodigo, BorderLayout.CENTER );
        painelCodigo.add( errorStrip, BorderLayout.LINE_END );
        
        carregarTemplate( "exemplo", true );

    }

    private RSyntaxTextArea criarTextAreaCodigo() {

        RSyntaxTextArea textAreaCodigo = new RSyntaxTextArea();
        textAreaCodigo.setTabSize( 4 );
        textAreaCodigo.setCaretPosition( 0 );
        textAreaCodigo.requestFocusInWindow();
        textAreaCodigo.setMarkOccurrences( true );
        textAreaCodigo.setCodeFoldingEnabled( true );
        textAreaCodigo.setClearWhitespaceLinesEnabled( false );
        textAreaCodigo.setMarginLineEnabled( true );

        InputMap im = textAreaCodigo.getInputMap();
        ActionMap am = textAreaCodigo.getActionMap();
        
        im.put( KeyStroke.getKeyStroke( KeyEvent.VK_MINUS, KeyEvent.CTRL_DOWN_MASK ), "decreaseFontSize" );
        im.put( KeyStroke.getKeyStroke( KeyEvent.VK_SUBTRACT, KeyEvent.CTRL_DOWN_MASK ), "decreaseFontSize" );
        am.put( "decreaseFontSize", new RSyntaxTextAreaEditorKit.DecreaseFontSizeAction() );
        
        im.put( KeyStroke.getKeyStroke( KeyEvent.VK_PLUS, KeyEvent.CTRL_DOWN_MASK ), "increaseFontSize" );
        im.put( KeyStroke.getKeyStroke( KeyEvent.VK_EQUALS, KeyEvent.CTRL_DOWN_MASK ), "increaseFontSize" );
        im.put( KeyStroke.getKeyStroke( KeyEvent.VK_ADD, KeyEvent.CTRL_DOWN_MASK ), "increaseFontSize" );
        am.put( "increaseFontSize", new RSyntaxTextAreaEditorKit.IncreaseFontSizeAction() );
        
        im.put( KeyStroke.getKeyStroke( KeyEvent.VK_0, KeyEvent.CTRL_DOWN_MASK ), "fontSizeToDefault" );
        im.put( KeyStroke.getKeyStroke( KeyEvent.VK_NUMPAD0, KeyEvent.CTRL_DOWN_MASK ), "fontSizeToDefault" );
        am.put( "fontSizeToDefault", new AbstractAction() {
            @Override
            public void actionPerformed( ActionEvent e ) {
                textAreaCodigo.setFont( fontePadrao );
            }
        });

        int ctrlShift = InputEvent.CTRL_DOWN_MASK | InputEvent.SHIFT_DOWN_MASK;
        im.put( KeyStroke.getKeyStroke( KeyEvent.VK_C, ctrlShift ), "copyAsStyledText" );
        am.put( "copyAsStyledText", new RSyntaxTextAreaEditorKit.CopyCutAsStyledTextAction( false ) );
        
        textAreaCodigo.getDocument().addDocumentListener( new DocumentListener() {
            
            @Override
            public void insertUpdate( DocumentEvent e ) {
                montarTitulo( true );
                atualizarBotoesDesfazerRefazer( textAreaCodigo );
            }

            @Override
            public void removeUpdate( DocumentEvent e ) {
                montarTitulo( true );
                atualizarBotoesDesfazerRefazer( textAreaCodigo );
            }

            @Override
            public void changedUpdate( DocumentEvent e ) {
                montarTitulo( true );
                atualizarBotoesDesfazerRefazer( textAreaCodigo );
            }
            
        });

        return textAreaCodigo;

    }

    private void desfazer() {
        textAreaCodigo.undoLastAction();
        atualizarBotoesDesfazerRefazer( textAreaCodigo );
    }
    
    private void refazer() {
        textAreaCodigo.redoLastAction();
        atualizarBotoesDesfazerRefazer( textAreaCodigo );
    }
    
    private void aumentarFonte( ActionEvent evt ) {
        Font f = textAreaCodigo.getFont();
        Font nf = new Font( f.getName(), f.getStyle(), f.getSize() == 40 ? 40 : f.getSize() + 1 );
        textAreaCodigo.setFont( nf );
    }
    
    private void diminuirFonte() {
        Font f = textAreaCodigo.getFont();
        Font nf = new Font( f.getName(), f.getStyle(), f.getSize() == 2 ? 2 : f.getSize() - 1 );
        textAreaCodigo.setFont( nf );
    }
    
    private void atualizarBotoesDesfazerRefazer(  RSyntaxTextArea textAreaCodigo ) {
        
        if ( textAreaCodigo.canUndo() ) {
            btnDesfazer.setEnabled( true );
            menuItemDesfazer.setEnabled( true );
        } else {
            btnDesfazer.setEnabled( false );
            menuItemDesfazer.setEnabled( false );
        }

        if ( textAreaCodigo.canRedo() ) {
            btnRefazer.setEnabled( true );
            menuItemRefazer.setEnabled( true );
        } else {
            btnRefazer.setEnabled( false );
            menuItemRefazer.setEnabled( false );
        }
                
    }
    
    private void executarCodigo() {
        
        try {
            
            String codigo = textAreaCodigo.getText().trim();
            //String codigo = new String( textArea.getText().trim().getBytes(), StandardCharsets.ISO_8859_1 );
            
            if ( !codigo.isEmpty() ) {
                
                AuroraLogoLexer lexer = new AuroraLogoLexer( 
                        CharStreams.fromString( textAreaCodigo.getText() ) );
                CommonTokenStream tokens = new CommonTokenStream( lexer );
                AuroraLogoParser parser = new AuroraLogoParser( tokens );
                ParseTree tree = parser.prog();

                DesenhistaAuroraLogoVisitor visitor = new DesenhistaAuroraLogoVisitor( tartaruga, this );
                visitor.visit( tree );
                
                //Utils.mostrarDados( null, parser, tree, true );
                
            } else {
                tartaruga.limpar();
            }
            
        } catch ( RecognitionException exc ) {
            tartaruga.limpar();
        } catch ( Exception exc ) {
            tartaruga.limpar();
        }
        
    }
    
    private void novoArquivo() {
        
        salvar( arquivoAtual );
        arquivoAtual = null;
        carregarTemplate( "novoArquivo", false );
        
        tartaruga.limpar();
        painelDesenho.repaint();
        
        montarTitulo( false );
        
    }
    
    private void abrirArquivo() {
        
        salvar( arquivoAtual );
        
        File diretorioAtual = new File( Utils.getPref( "CAMINHO_ABRIR_SALVAR" ) );
        JFileChooser jfc = new JFileChooser( diretorioAtual );
        jfc.setDialogTitle( "Abrir..." );
        jfc.setMultiSelectionEnabled( false );
        jfc.removeChoosableFileFilter( jfc.getFileFilter() );
        jfc.setFileFilter( filtroExtensao );

        if ( jfc.showOpenDialog( this ) == JFileChooser.APPROVE_OPTION ) {

            File arquivo = jfc.getSelectedFile();
            arquivoAtual = arquivo;
            carregarArquivo( arquivo, true );

        }
        
        montarTitulo( false );
        
    }
    
    private void salvarArquivo() {
        
        if ( arquivoAtual == null ) {
            fragmentoSalvar( "Salvar..." );
        }
        
        salvar( arquivoAtual );
        
    }
    
    
    private void salvarArquivoComo() {
        
        salvar( arquivoAtual );
        fragmentoSalvar( "Salvar Como..." );
        salvar( arquivoAtual );
        
    }
    
    private void salvar( File arquivo ) {
        
        if ( arquivo != null ) {
            try ( PrintStream ps = new PrintStream( new FileOutputStream( arquivo ) ) ) {
                ps.print( textAreaCodigo.getText() );
            } catch ( FileNotFoundException exc ) {
                exc.printStackTrace();
            }
        }
        
        montarTitulo( false );
        
    }
    
    private void fragmentoSalvar( String tituloDialogo ) {
        
        File diretorioAtual = new File( Utils.getPref( "CAMINHO_ABRIR_SALVAR" ) );
        JFileChooser jfc = new JFileChooser( diretorioAtual );
        jfc.setDialogTitle( tituloDialogo );
        jfc.setMultiSelectionEnabled( false );
        jfc.removeChoosableFileFilter( jfc.getFileFilter() );
        jfc.setFileFilter( filtroExtensao );

        if ( jfc.showSaveDialog( this ) == JFileChooser.APPROVE_OPTION ) {

            File arquivo = jfc.getSelectedFile();
            boolean salvar = true;

            if ( arquivo.exists() ) {
                if ( JOptionPane.showConfirmDialog( null, 
                        "O arquivo já existe, deseja sobrescrevê-lo?", 
                        "Confirmação", 
                        JOptionPane.YES_NO_OPTION ) == JOptionPane.NO_OPTION ) {
                    salvar = false;
                }
            } else {
                if ( !arquivo.getName().endsWith( ".aulg" ) ) {
                    arquivo = new File( arquivo.getAbsolutePath() + ".aulg" );
                }
            }

            if ( salvar ) {

                Utils.setPref( "CAMINHO_ABRIR_SALVAR", arquivo.getParentFile().getAbsolutePath() );
                arquivoAtual = arquivo;

            }

        }
        
    }
    
    private void executar() {
        
        salvar( arquivoAtual );
        tartaruga.setEstadoAtual( 0 );
        tartaruga.setPassoAPasso( false );
        executarCodigo();
        painelDesenho.repaint();
        
    }
    
    private void executarPassoAPassoAutomatico() {
        
        salvar( arquivoAtual );
        tartaruga.setEstadoAtual( 0 );
        tartaruga.setPassoAPasso( true );
        executarCodigo();
        
        new Thread( new Runnable() {
            @Override
            public void run() {
                
                pararPassoAPassoAutomatico = false;
                
                while ( !tartaruga.estadoFinal() && !pararPassoAPassoAutomatico ) {
                    EventQueue.invokeLater( new Runnable() {
                        public void run() {
                            tartaruga.proximoEstado();
                            painelDesenho.repaint();
                        }
                    });
                    try {
                        Thread.sleep( 1000 / sliderQuadrosPorSegundo.getValue() );
                    } catch ( InterruptedException exc ) {
                    }
                }
                
            }
        }).start();
        
        painelDesenho.repaint();
        
    }
    
    private void sair() {
        
        if ( PRODUCAO ) {
            
            salvarArquivo();

            if ( JOptionPane.showConfirmDialog( 
                    this, 
                    "Deseja mesmo sair?", "Sair", 
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE ) == JOptionPane.YES_OPTION ) {
                System.exit( 0 );
            }
        
        } else {
            System.exit( 0 );
        }
        
    }
    
    private void carregarTemplate( String template, boolean inicio ) {
        
        try ( Scanner s = new Scanner( 
                getClass().getResourceAsStream( "/br/com/davidbuzatto/auroralogo/templates/" 
                        + template + ".aulg" ), StandardCharsets.UTF_8 )) {
            carregar( s, inicio );
        }
        
    }
    
    private void carregarArquivo( File arquivo, boolean inicio ) {
        
        try ( Scanner s = new Scanner( arquivo, StandardCharsets.UTF_8 ) ) {
            carregar( s, inicio );
        } catch ( IOException exc ) {
            exc.printStackTrace();
        }
        
    }
    
    private void carregar( Scanner s, boolean inicio ) {
        
        StringBuilder sb = sb = new StringBuilder();
        sb.append( s.nextLine() );
        while ( s.hasNextLine() ) {
            sb.append( "\n" ).append( s.nextLine() );
        }
        
        String codigo = sb.toString();
        String data = new SimpleDateFormat( 
                "dd/MM/yyyy", Locale.forLanguageTag( "pt-BR" ) ).format( 
                        new Date() );
        
        codigo = codigo.replace( "<USUARIO>", System.getProperty( "user.name" ) );
        codigo = codigo.replace( "<DATA>", data );
        
        textAreaCodigo.setText( codigo );
        textAreaCodigo.setCaretPosition( inicio ? 0 : textAreaCodigo.getText().length() );
        
    }
    
    private void configurarTemaTextAreaCodigoClaro() {
        try {
            Theme t = Theme.load( getClass().getResourceAsStream( "/br/com/davidbuzatto/auroralogo/gui/temasrsta/claro.xml" ) );
            t.apply( textAreaCodigo );
        } catch ( IOException exc ) {
            exc.printStackTrace();
        }
    }
    
    private void configurarTemaTextAreaCodigoEscuro() {
        try {
            Theme t = Theme.load( getClass().getResourceAsStream( "/br/com/davidbuzatto/auroralogo/gui/temasrsta/escuro.xml" ) );
            t.apply( textAreaCodigo );
        } catch ( IOException exc ) {
            exc.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main( String args[] ) {

        Utils.preparePreferences();
        
        FlatIntelliJLaf.setup();
        
        EventQueue.invokeLater( new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible( true );
            }
        } );

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar barraFerramentas;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnAnteriorPassoAPasso;
    private javax.swing.JButton btnAumentarFonte;
    private javax.swing.JToggleButton btnDepurador;
    private javax.swing.JButton btnDesfazer;
    private javax.swing.JButton btnDiminuirFonte;
    private javax.swing.JButton btnExecutar;
    private javax.swing.JButton btnExecutarPassoAPasso;
    private javax.swing.JButton btnExecutarPassoAPassoAutomatico;
    private javax.swing.ButtonGroup btnGroupTemas;
    private javax.swing.JButton btnInicioPassoAPasso;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPararExecutarPassoAutomatico;
    private javax.swing.JButton btnPararPassoAPasso;
    private javax.swing.JButton btnProximoPassoAPasso;
    private javax.swing.JButton btnRefazer;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSalvarComo;
    private javax.swing.JButton btnUltimoPassoAPasso;
    private javax.swing.JLabel lblQuadrosPorSegundo;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenu menuExecutar;
    private javax.swing.JMenu menuExemplos;
    private javax.swing.JMenuItem menuItemAbrir;
    private javax.swing.JMenuItem menuItemAumentarFonte;
    private javax.swing.JCheckBoxMenuItem menuItemCBDepurador;
    private javax.swing.JMenuItem menuItemColar;
    private javax.swing.JMenuItem menuItemConfiguracoes1;
    private javax.swing.JMenuItem menuItemCopiar;
    private javax.swing.JMenuItem menuItemCopiarTextoFormatado;
    private javax.swing.JMenuItem menuItemDesfazer;
    private javax.swing.JMenuItem menuItemDiminuirFonte;
    private javax.swing.JMenuItem menuItemExecutar;
    private javax.swing.JMenuItem menuItemExecutarPassoAPasso;
    private javax.swing.JMenuItem menuItemExecutarPassoAPassoAutomatico;
    private javax.swing.JMenuItem menuItemNovo;
    private javax.swing.JRadioButtonMenuItem menuItemRTemaClaro;
    private javax.swing.JRadioButtonMenuItem menuItemRTemaEscuro;
    private javax.swing.JMenuItem menuItemRecortar;
    private javax.swing.JMenuItem menuItemRefazer;
    private javax.swing.JMenuItem menuItemSalvar;
    private javax.swing.JMenuItem menuItemSalvarComo;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JPanel painelCodigo;
    private br.com.davidbuzatto.auroralogo.gui.PainelDesenho painelDesenho;
    private javax.swing.Box.Filler preenchimento;
    private javax.swing.JToolBar.Separator separador1;
    private javax.swing.JToolBar.Separator separador2;
    private javax.swing.JToolBar.Separator separador3;
    private javax.swing.JToolBar.Separator separador4;
    private javax.swing.JToolBar.Separator separador5;
    private javax.swing.JPopupMenu.Separator separadorMenuArquivo1;
    private javax.swing.JPopupMenu.Separator separadorMenuEditar1;
    private javax.swing.JPopupMenu.Separator separadorMenuEditar2;
    private javax.swing.JPopupMenu.Separator separadorMenuEditar3;
    private javax.swing.JPopupMenu.Separator separadorMenuExecutar1;
    private javax.swing.JSlider sliderQuadrosPorSegundo;
    private javax.swing.JMenu submenuTemas;
    // End of variables declaration//GEN-END:variables
}
